### ISSUE TITLE
Compilation error on linux, gcc 12.2.0

### ISSUE THREAD

**Issue by legalize-nuke-bombs** [Hapaxia/SfmlTextAline#8]
Everything works fine on Windows msvc, but gcc 12.2.0 (linux) produces this output:
`/home/user/BattleForDawnridge/src/SfmlTextAline/SfmlTextAline.cpp:46:71: error: pasting "&" and "font" does not give a valid preprocessing token
   46 | #define SET_AND_UPDATE_MEMBER_IF_DIFFERENT_PTR(x) do { if ((m_##x) != &##x) { ((m_##x) = &##x); m_isUpdateRequired = true; } } while(0)
      |                                                                       ^
/home/user/BattleForDawnridge/src/SfmlTextAline/SfmlTextAline.cpp:163:9: note: in expansion of macro ‘SET_AND_UPDATE_MEMBER_IF_DIFFERENT_PTR’
  163 |         SET_AND_UPDATE_MEMBER_IF_DIFFERENT_PTR(font);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/user/BattleForDawnridge/src/SfmlTextAline/SfmlTextAline.cpp:46:90: error: pasting "&" and "font" does not give a valid preprocessing token
   46 | #define SET_AND_UPDATE_MEMBER_IF_DIFFERENT_PTR(x) do { if ((m_##x) != &##x) { ((m_##x) = &##x); m_isUpdateRequired = true; } } while(0)
      |                                                                                          ^
/home/user/BattleForDawnridge/src/SfmlTextAline/SfmlTextAline.cpp:163:9: note: in expansion of macro ‘SET_AND_UPDATE_MEMBER_IF_DIFFERENT_PTR’
  163 |         SET_AND_UPDATE_MEMBER_IF_DIFFERENT_PTR(font);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
`

**Comment by Hapaxia** [comment]
I should be less lazy and unfold these macros to be the exact code desired.

I'm interested to know why the two compilers treat the macro differently though.
